package pokemon

import (
	"testing"

	"github.com/JoshGuarino/PokeGo/pkg/models"
	"github.com/joshguarino/poketool/internal"
	"github.com/stretchr/testify/assert"
)

var controller internal.IController = NewController()

func TestGetList(t *testing.T) {
	rAbilities, _ := controller.GetList("Abilities", 20, 0)
	rCharacteristics, _ := controller.GetList("Characteristics", 20, 0)
	rEgg, _ := controller.GetList("Egg Groups", 20, 0)
	rGender, _ := controller.GetList("Genders", 20, 0)
	rGrowth, _ := controller.GetList("Growth Rates", 20, 0)
	rNatures, _ := controller.GetList("Natures", 20, 0)
	rPokeathlon, _ := controller.GetList("Pokeathlon Stats", 20, 0)
	rPokemon, _ := controller.GetList("Pokemon", 20, 0)
	rColors, _ := controller.GetList("Pokemon Colors", 20, 0)
	rForms, _ := controller.GetList("Pokemon Forms", 20, 0)
	rHabitats, _ := controller.GetList("Pokemon Habitats", 20, 0)
	rShapes, _ := controller.GetList("Pokemon Shapes", 20, 0)
	rSpecies, _ := controller.GetList("Pokemon Species", 20, 0)
	rStats, _ := controller.GetList("Stats", 20, 0)
	rTypes, _ := controller.GetList("Types", 20, 0)
	_, err := controller.GetList("test", 20, 0)
	assert.IsType(t, &models.NamedResourceList{}, rAbilities, "Expected to have type 'NamedResourceList' struct.")
	assert.NotEmpty(t, rAbilities, "Expected to not have an empty struct.")
	assert.IsType(t, &models.ResourceList{}, rCharacteristics, "Expected to have type 'ResourceList' struct.")
	assert.NotEmpty(t, rCharacteristics, "Expected to not have an empty struct.")
	assert.IsType(t, &models.NamedResourceList{}, rEgg, "Expected to have type 'NamedResourceList' struct.")
	assert.NotEmpty(t, rEgg, "Expected to not have an empty struct.")
	assert.IsType(t, &models.NamedResourceList{}, rGender, "Expected to have type 'NamedResourceList' struct.")
	assert.NotEmpty(t, rGender, "Expected to not have an empty struct.")
	assert.IsType(t, &models.NamedResourceList{}, rGrowth, "Expected to have type 'NamedResourceList' struct.")
	assert.NotEmpty(t, rGrowth, "Expected to not have an empty struct.")
	assert.IsType(t, &models.NamedResourceList{}, rNatures, "Expected to have type 'NamedResourceList' struct.")
	assert.NotEmpty(t, rNatures, "Expected to not have an empty struct.")
	assert.IsType(t, &models.NamedResourceList{}, rPokeathlon, "Expected to have type 'NamedResourceList' struct.")
	assert.NotEmpty(t, rPokeathlon, "Expected to not have an empty struct.")
	assert.IsType(t, &models.NamedResourceList{}, rPokemon, "Expected to have type 'NamedResourceList' struct.")
	assert.NotEmpty(t, rPokemon, "Expected to not have an empty struct.")
	assert.IsType(t, &models.NamedResourceList{}, rColors, "Expected to have type 'NamedResourceList' struct.")
	assert.NotEmpty(t, rColors, "Expected to not have an empty struct.")
	assert.IsType(t, &models.NamedResourceList{}, rForms, "Expected to have type 'NamedResourceList' struct.")
	assert.NotEmpty(t, rForms, "Expected to not have an empty struct.")
	assert.IsType(t, &models.NamedResourceList{}, rHabitats, "Expected to have type 'NamedResourceList' struct.")
	assert.NotEmpty(t, rHabitats, "Expected to not have an empty struct.")
	assert.IsType(t, &models.NamedResourceList{}, rShapes, "Expected to have type 'NamedResourceList' struct.")
	assert.NotEmpty(t, rShapes, "Expected to not have an empty struct.")
	assert.IsType(t, &models.NamedResourceList{}, rSpecies, "Expected to have type 'NamedResourceList' struct.")
	assert.NotEmpty(t, rSpecies, "Expected to not have an empty struct.")
	assert.IsType(t, &models.NamedResourceList{}, rStats, "Expected to have type 'NamedResourceList' struct.")
	assert.NotEmpty(t, rStats, "Expected to not have an empty struct.")
	assert.IsType(t, &models.NamedResourceList{}, rTypes, "Expected to have type 'NamedResourceList' struct.")
	assert.Error(t, err, "Expected an error to be thrown.")
}

func TestGetSpecific(t *testing.T) {
	rAbilities, _ := controller.GetSpecific("Abilities", "1")
	rCharacteristics, _ := controller.GetSpecific("Characteristics", "1")
	rEgg, _ := controller.GetSpecific("Egg Groups", "1")
	rGender, _ := controller.GetSpecific("Genders", "1")
	rGrowth, _ := controller.GetSpecific("Growth Rates", "1")
	rNatures, _ := controller.GetSpecific("Natures", "1")
	rPokeathlon, _ := controller.GetSpecific("Pokeathlon Stats", "1")
	rPokemon, _ := controller.GetSpecific("Pokemon", "1")
	rColors, _ := controller.GetSpecific("Pokemon Colors", "1")
	rForms, _ := controller.GetSpecific("Pokemon Forms", "1")
	rHabitats, _ := controller.GetSpecific("Pokemon Habitats", "1")
	rShapes, _ := controller.GetSpecific("Pokemon Shapes", "1")
	rSpecies, _ := controller.GetSpecific("Pokemon Species", "1")
	rStats, _ := controller.GetSpecific("Stats", "1")
	rTypes, _ := controller.GetSpecific("Types", "1")
	_, err := controller.GetSpecific("test", "test")
	assert.IsType(t, &models.Ability{}, rAbilities, "Expected to have type 'Ability' struct.")
	assert.IsType(t, &models.Characteristic{}, rCharacteristics, "Expected to have type 'Characteristic' struct.")
	assert.IsType(t, &models.EggGroup{}, rEgg, "Expected to have type 'EggGroup' struct.")
	assert.IsType(t, &models.Gender{}, rGender, "Expected to have type 'Gender' struct.")
	assert.IsType(t, &models.GrowthRate{}, rGrowth, "Expected to have type 'GrowthRate' struct.")
	assert.IsType(t, &models.Nature{}, rNatures, "Expected to have type 'Nature' struct.")
	assert.IsType(t, &models.PokeathlonStat{}, rPokeathlon, "Expected to have type 'PokeathlonStat' struct.")
	assert.IsType(t, &models.Pokemon{}, rPokemon, "Expected to have type 'Pokemon' struct.")
	assert.IsType(t, &models.PokemonColor{}, rColors, "Expected to have type 'PokemonColor' struct.")
	assert.IsType(t, &models.PokemonForm{}, rForms, "Expected to have type 'PokemonForm' struct.")
	assert.IsType(t, &models.PokemonHabitat{}, rHabitats, "Expected to have type 'PokemonHabitat' struct.")
	assert.IsType(t, &models.PokemonShape{}, rShapes, "Expected to have type 'PokemonShape' struct.")
	assert.IsType(t, &models.PokemonSpecies{}, rSpecies, "Expected to have type 'PokemonSpecies' struct.")
	assert.IsType(t, &models.Stat{}, rStats, "Expected to have type 'Stat' struct.")
	assert.IsType(t, &models.Type{}, rTypes, "Expected to have type 'Type' struct.")
	assert.Error(t, err, "Expected an error to be thrown.")
}
